name: Test Docker Swarm with Vagrant

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  vagrant:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        # Instalar dependências do Vagrant e VirtualBox
        sudo apt-get update
        sudo apt-get install -y virtualbox

        # Baixar a versão 2.4.3-1 do Vagrant
        if [ ! -f vagrant_2.4.3-1_amd64.deb ]; then
          curl -LO https://releases.hashicorp.com/vagrant/2.4.3/vagrant_2.4.3-1_amd64.deb
        
          # Verificar se o arquivo foi baixado corretamente
          ls -l vagrant_2.4.3-1_amd64.deb
        
          # Instalar o pacote .deb do Vagrant
          sudo dpkg -i vagrant_2.4.3-1_amd64.deb
        
          # Corrigir dependências caso necessário
          sudo apt-get install -f
        fi

    # Cache do diretório .vagrant (impede recriação das máquinas a cada execução)
    - name: Cache Vagrant directory
      uses: actions/cache@v4
      with:
        path: .vagrant
        key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile', '**/*.sh') }}
        restore-keys: |
          ${{ runner.os }}-vagrant-

    - name: Initialize and start Vagrant
      run: |
        # Inicializa e sobe as VMs definidas no Vagrantfile
        vagrant up --provider=virtualbox

    # Passo para destruir as máquinas após a execução
    - name: Destroy Vagrant machines
      run: |
        vagrant destroy -f  # O "-f" força a destruição sem pedir confirmação
