name: Test Docker Swarm with Vagrant

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  vagrant:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        # Instalar dependências do VirtualBox e Vagrant
        sudo apt-get update
        sudo apt-get install -y virtualbox
        # Baixar e instalar o Vagrant
        curl -O https://releases.hashicorp.com/vagrant/2.4.3/vagrant_2.4.3-1_amd64.deb
        sudo dpkg -i vagrant_2.4.3-1_amd64.deb
        sudo apt-get install -f # Corrige dependências quebradas, se necessário

    - name: Initialize and start Vagrant
      run: |
        # Inicializa e sobe as VMs definidas no Vagrantfile
        vagrant up --provider=virtualbox
