name: Test Docker Swarm with Vagrant

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  vagrant:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # Cache do arquivo do Vagrant (.deb)
    - name: Cache Vagrant package
      uses: actions/cache@v2
      with:
        path: ~/.cache/vagrant
        key: ${{ runner.os }}-vagrant-${{ hashFiles('**/vagrant_2.4.3-1_amd64.deb') }}
        restore-keys: |
          ${{ runner.os }}-vagrant-

    # Instalar dependências (apenas se o Vagrant não for cacheado)
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y virtualbox

        # Baixar e instalar o Vagrant apenas se não estiver cacheado
        if [ ! -f vagrant_2.4.3-1_amd64.deb ]; then
          curl -LO https://releases.hashicorp.com/vagrant/2.4.3/vagrant_2.4.3-1_amd64.deb
          sudo dpkg -i vagrant_2.4.3-1_amd64.deb
          sudo apt-get install -f
        fi

    # Cache do diretório .vagrant (impede recriação das máquinas a cada execução)
    - name: Cache Vagrant directory
      uses: actions/cache@v2
      with:
        path: .vagrant
        key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
        restore-keys: |
          ${{ runner.os }}-vagrant-

    - name: Initialize and start Vagrant
      run: |
        # Inicializa e sobe as VMs definidas no Vagrantfile
        vagrant up --provider=virtualbox
